import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    margin: 0,
    background: '#030712',
    color: '#e5e7eb',
    display: 'block',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    padding: 0,
  },
  card: {
    width: '100vw',
    minHeight: '100vh',
    background: '#030712',
    display: 'flex',
    flexDirection: 'column',
  },
  dashboardShell: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.55fr) minmax(360px, 1fr)',
    flex: 1,
    minHeight: 0,
  },
  settingsLayout: {
    marginTop: '16px',
    display: 'grid',
    gridTemplateColumns: '220px minmax(0, 1fr)',
    gap: '16px',
    alignItems: 'start',
  },
  settingsNav: {
    display: 'grid',
    gap: '8px',
  },
  settingsNavButton: {
    width: '100%',
    textAlign: 'left',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    color: '#cbd5e1',
    borderRadius: '12px',
    padding: '12px 14px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  settingsNavButtonActive: {
    width: '100%',
    textAlign: 'left',
    background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.16), rgba(59, 130, 246, 0.12))',
    border: '1px solid #38bdf8',
    color: '#eff6ff',
    borderRadius: '12px',
    padding: '12px 14px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 700,
  },
  topBar: {
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '0 16px',
    background: '#111827',
    borderBottom: '1px solid #1f2937',
    flexShrink: 0,
  },
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginRight: '8px',
  },
  brandBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '10px',
    background: '#7c3aed',
    color: '#ffffff',
    display: 'grid',
    placeItems: 'center',
    fontSize: '13px',
    fontWeight: 700,
  },
  topBarTitle: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 700,
  },
  topBarMeta: {
    margin: '1px 0 0',
    color: '#6b7280',
    fontSize: '11px',
  },
  topNav: {
    display: 'flex',
    gap: '4px',
  },
  topNavButton: {
    background: 'transparent',
    border: 'none',
    color: '#9ca3af',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  topNavButtonActive: {
    background: '#7c3aed',
    border: 'none',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  topActions: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  topGhostButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  liveButton: {
    background: '#dc2626',
    border: '1px solid #ef4444',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  block: {
    marginTop: '16px',
    borderTop: '1px solid #1f2937',
    paddingTop: '16px',
  },
  subtitle: {
    margin: 0,
    fontSize: '18px',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '16px',
    color: '#e5e7eb',
  },
  settingsSection: {
    marginTop: '14px',
    display: 'grid',
    gap: '10px',
  },
  settingsGrid: {
    marginTop: '14px',
    display: 'grid',
    gap: '14px',
  },
  previewCard: {
    background: 'linear-gradient(180deg, rgba(17,24,39,0.98), rgba(11,16,32,0.96))',
    border: '1px solid #243041',
    borderRadius: '14px',
    padding: '16px',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
  },
  previewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  message: {
    margin: '8px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
  },
  helper: {
    margin: '6px 0 0',
    color: '#6b7280',
    fontSize: '12px',
    lineHeight: 1.5,
  },
  error: {
    margin: '12px 0 0',
    color: '#fca5a5',
    fontSize: '14px',
  },
  list: {
    marginTop: '8px',
    display: 'grid',
    gap: '8px',
  },
  profileButton: {
    background: '#111827',
    border: '1px solid #374151',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  profileButtonActive: {
    background: '#1e1b4b',
    border: '1px solid #8b5cf6',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  feedCard: {
    background: '#030712',
    borderRight: '1px solid #1f2937',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  feedHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 16px',
    borderBottom: '1px solid #1f2937',
    flexShrink: 0,
  },
  feedTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  chatModeToggle: {
    display: 'inline-flex',
    background: '#111827',
    border: '1px solid #374151',
    borderRadius: '10px',
    padding: '2px',
  },
  chatModeButton: {
    background: 'transparent',
    border: 'none',
    color: '#9ca3af',
    borderRadius: '8px',
    padding: '6px 10px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  chatModeButtonActive: {
    background: '#7c3aed',
    border: 'none',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '6px 10px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  platformFilterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  platformFilterDot: {
    width: '30px',
    height: '30px',
    borderRadius: '10px',
    border: '1px solid #374151',
    display: 'grid',
    placeItems: 'center',
    fontSize: '10px',
    fontWeight: 700,
  },
  feedScroll: {
    flex: 1,
    overflowY: 'auto',
    display: 'grid',
    gap: '2px',
    padding: '6px 0',
  },
  chatItem: {
    display: 'grid',
    gap: '4px',
    padding: '10px 14px',
    background: 'rgba(15, 23, 42, 0.32)',
    borderBottom: '1px solid rgba(31, 41, 55, 0.65)',
  },
  chatMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    fontSize: '12px',
    color: '#94a3b8',
  },
  chatBody: {
    margin: 0,
    color: '#e5e7eb',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
    minHeight: '32px',
    padding: '0 16px',
    background: '#111827',
    borderTop: '1px solid #1f2937',
    color: '#6b7280',
    fontSize: '12px',
    flexShrink: 0,
  },
  statusLine: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    color: '#9ca3af',
    fontSize: '12px',
  },
  statusDivider: {
    color: '#4b5563',
  },
  sideStack: {
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    minHeight: 0,
  },
  obsPanel: {
    padding: '16px',
    borderBottom: '1px solid #1f2937',
  },
  obsPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '14px',
    gap: '12px',
  },
  obsLiveBadge: {
    color: '#f87171',
    fontSize: '12px',
    fontWeight: 700,
  },
  obsOfflineBadge: {
    color: '#6b7280',
    fontSize: '12px',
    fontWeight: 700,
  },
  obsStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '8px',
    marginBottom: '10px',
  },
  obsStatCard: {
    background: 'rgba(31, 41, 55, 0.7)',
    borderRadius: '12px',
    padding: '10px',
    textAlign: 'center',
    display: 'grid',
    gap: '4px',
  },
  obsStatValueLabel: {
    color: '#6b7280',
    fontSize: '11px',
  },
  obsStatValuePrimary: {
    color: '#a78bfa',
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  obsStatSuffix: {
    color: '#6b7280',
    fontSize: '12px',
    fontWeight: 500,
  },
  obsConnectionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'rgba(31, 41, 55, 0.7)',
    borderRadius: '12px',
    padding: '10px 12px',
    marginBottom: '10px',
  },
  obsConnectionLabel: {
    color: '#6b7280',
    fontSize: '12px',
    minWidth: '70px',
  },
  obsConnectionTrack: {
    flex: 1,
    height: '6px',
    background: '#374151',
    borderRadius: '999px',
    overflow: 'hidden',
  },
  obsConnectionFill: {
    height: '100%',
    background: '#22c55e',
    borderRadius: '999px',
  },
  obsConnectionPercent: {
    color: '#d1d5db',
    fontSize: '12px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  viewerCardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
    gap: '8px',
  },
  viewerCard: {
    border: '1px solid #374151',
    borderRadius: '16px',
    padding: '12px 10px',
    display: 'grid',
    gap: '6px',
    textAlign: 'center',
  },
  viewerCardLabel: {
    fontSize: '11px',
    fontWeight: 700,
  },
  viewerCardValue: {
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  viewerCardMeta: {
    color: '#9ca3af',
    fontSize: '11px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
  },
  statCard: {
    padding: '12px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    display: 'grid',
    gap: '6px',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: '12px',
  },
  statValue: {
    color: '#f8fafc',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueGood: {
    color: '#4ade80',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueWarn: {
    color: '#facc15',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueBad: {
    color: '#f87171',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  platformCard: {
    padding: '14px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    display: 'grid',
    gap: '10px',
  },
  platformHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  tableWrap: {
    overflowX: 'auto',
    borderRadius: '14px',
    border: '1px solid rgba(51, 65, 85, 0.8)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
  },
  tableHeadCell: {
    textAlign: 'left',
    padding: '12px',
    borderBottom: '1px solid rgba(51, 65, 85, 0.8)',
    color: '#94a3b8',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    background: 'rgba(15, 23, 42, 0.94)',
  },
  tableCell: {
    padding: '12px',
    borderBottom: '1px solid rgba(30, 41, 59, 0.8)',
    color: '#e2e8f0',
    verticalAlign: 'top',
  },
  codeText: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    color: '#e9d5ff',
  },
  modalShell: {
    marginTop: '14px',
    padding: '16px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.88)',
    border: '1px solid rgba(56, 189, 248, 0.28)',
    display: 'grid',
    gap: '12px',
  },
  textArea: {
    width: '100%',
    minHeight: '92px',
    background: '#0f172a',
    border: '1px solid #334155',
    color: '#e5e7eb',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '14px',
    resize: 'vertical',
  },
  tokenField: {
    width: '100%',
    background: '#0f172a',
    border: '1px solid #334155',
    color: '#cbd5e1',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  toastStack: {
    position: 'fixed',
    top: '16px',
    right: '16px',
    display: 'grid',
    gap: '10px',
    zIndex: 80,
  },
  toast: {
    minWidth: '260px',
    maxWidth: '360px',
    background: 'rgba(15, 23, 42, 0.96)',
    border: '1px solid rgba(248, 113, 113, 0.5)',
    borderRadius: '14px',
    padding: '12px 14px',
    color: '#fecaca',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.35)',
    display: 'grid',
    gap: '6px',
  },
  toastTitle: {
    color: '#fee2e2',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  eventBanner: {
    display: 'grid',
    gap: '6px',
    padding: '12px',
    borderRadius: '12px',
    background: 'rgba(17, 24, 39, 0.78)',
    border: '1px solid rgba(55, 65, 81, 0.85)',
  },
  eventHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  eventTitle: {
    color: '#f8fafc',
    fontSize: '14px',
    fontWeight: 700,
  },
  eventText: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  path: {
    color: '#9ca3af',
    fontSize: '12px',
    wordBreak: 'break-all',
  },
  secondaryButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  actionsRow: {
    marginTop: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  dangerButton: {
    background: '#3f1d2e',
    border: '1px solid #7f1d1d',
    color: '#fecaca',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.65)',
    display: 'grid',
    placeItems: 'center',
    padding: '24px',
  },
  modalCard: {
    width: 'min(520px, 100%)',
    background: '#111827',
    border: '1px solid #374151',
    borderRadius: '12px',
    padding: '20px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '22px',
    fontWeight: 700,
  },
  label: {
    marginTop: '16px',
    display: 'grid',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  searchInput: {
    width: '100%',
    background: '#0f172a',
    border: '1px solid #334155',
    color: '#e5e7eb',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '14px',
  },
  select: {
    background: '#1f2937',
    border: '1px solid #4b5563',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
  },
  checkboxLabel: {
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  pickerSurface: {
    marginTop: '10px',
    display: 'grid',
    gap: '10px',
    padding: '12px',
    background: 'rgba(15, 23, 42, 0.82)',
    border: '1px solid #243041',
    borderRadius: '12px',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  chip: {
    background: 'rgba(30, 41, 59, 0.95)',
    border: '1px solid #334155',
    color: '#cbd5e1',
    borderRadius: '999px',
    padding: '7px 11px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600,
  },
  chipActive: {
    background: 'rgba(14, 165, 233, 0.18)',
    border: '1px solid #38bdf8',
    color: '#e0f2fe',
    borderRadius: '999px',
    padding: '7px 11px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
  },
  selectionPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(14, 165, 233, 0.12)',
    border: '1px solid rgba(56, 189, 248, 0.35)',
    color: '#bae6fd',
    borderRadius: '999px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  listbox: {
    display: 'grid',
    gap: '8px',
    maxHeight: '230px',
    overflowY: 'auto',
  },
  listboxButton: {
    width: '100%',
    background: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid #243041',
    color: '#e5e7eb',
    borderRadius: '12px',
    padding: '12px',
    cursor: 'pointer',
    textAlign: 'left',
    display: 'grid',
    gap: '2px',
  },
  listboxButtonActive: {
    width: '100%',
    background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.18), rgba(14, 165, 233, 0.1))',
    border: '1px solid #38bdf8',
    color: '#f8fafc',
    borderRadius: '12px',
    padding: '12px',
    cursor: 'pointer',
    textAlign: 'left',
    display: 'grid',
    gap: '2px',
  },
  listboxMeta: {
    color: '#94a3b8',
    fontSize: '12px',
  },
  modalActions: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  primaryButton: {
    background: '#7c3aed',
    border: '1px solid #8b5cf6',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '10px 14px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
  },
  activityCard: {
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    minHeight: 0,
  },
  activityHeader: {
    padding: '16px',
    borderBottom: '1px solid #1f2937',
  },
  activityList: {
    overflowY: 'auto',
    display: 'grid',
    gap: '10px',
    padding: '12px 16px 16px',
  },
  settingsWorkspaceShell: {
    height: '100%',
    display: 'flex',
    minHeight: 0,
  },
  settingsSidebar: {
    width: '224px',
    background: '#111827',
    borderRight: '1px solid #1f2937',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
  },
  settingsSidebarHeader: {
    padding: '12px 16px',
    borderBottom: '1px solid #1f2937',
  },
  settingsSidebarTitle: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 600,
    color: '#d1d5db',
  },
  settingsSidebarNav: {
    flex: 1,
    overflowY: 'auto',
    padding: '8px 0',
  },
  settingsSidebarGroup: {
    padding: '0 12px 4px',
  },
  settingsSidebarGroupLabel: {
    margin: '0 0 4px',
    padding: '4px 8px',
    color: '#4b5563',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  settingsSidebarButton: {
    width: '100%',
    textAlign: 'left',
    background: 'transparent',
    border: 'none',
    color: '#9ca3af',
    borderRadius: '8px',
    padding: '10px 12px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
  },
  settingsSidebarButtonActive: {
    width: '100%',
    textAlign: 'left',
    background: '#1f2937',
    border: 'none',
    color: '#f9fafb',
    borderRadius: '8px',
    padding: '10px 12px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
  },
  settingsContentArea: {
    flex: 1,
    overflowY: 'auto',
    minWidth: 0,
  },
  settingsPage: {
    padding: '24px',
    width: '100%',
  },
  settingsPageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '20px',
  },
  settingsPageTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: '#f3f4f6',
  },
  settingsPageDescription: {
    margin: '4px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
    lineHeight: 1.5,
  },
  settingsPageAction: {
    flexShrink: 0,
  },
  settingsColumn: {
    display: 'grid',
    gap: '16px',
  },
  settingsSurface: {
    background: 'rgba(31, 41, 55, 0.4)',
    border: '1px solid #374151',
    borderRadius: '16px',
    padding: '20px',
    display: 'grid',
    gap: '14px',
  },
  settingsSurfaceTable: {
    background: 'rgba(31, 41, 55, 0.4)',
    border: '1px solid #374151',
    borderRadius: '16px',
    padding: '20px',
    display: 'grid',
    gap: '16px',
    overflow: 'hidden',
  },
  settingsSurfaceHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  settingsSubsectionTitle: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 600,
    color: '#f3f4f6',
  },
  settingsSecondaryText: {
    margin: 0,
    color: '#6b7280',
    fontSize: '12px',
    lineHeight: 1.5,
  },
  settingsInfoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '12px',
  },
  settingsInfoTile: {
    background: 'rgba(31, 41, 55, 0.4)',
    border: '1px solid #374151',
    borderRadius: '14px',
    padding: '16px',
    display: 'grid',
    gap: '8px',
  },
  settingsInfoLabel: {
    margin: 0,
    color: '#6b7280',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  settingsInfoText: {
    margin: 0,
    color: '#f3f4f6',
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1.35,
  },
  settingsToggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '20px',
    borderTop: '1px solid #374151',
    paddingTop: '16px',
  },
  settingsToggleTitle: {
    margin: 0,
    color: '#f3f4f6',
    fontSize: '14px',
    fontWeight: 500,
  },
  settingsToggleDescription: {
    margin: '4px 0 0',
    color: '#6b7280',
    fontSize: '12px',
    lineHeight: 1.5,
  },
  toggleSwitch: {
    position: 'relative',
    width: '36px',
    height: '20px',
    display: 'inline-flex',
    flexShrink: 0,
    cursor: 'pointer',
  },
  toggleInput: {
    opacity: 0,
    width: 0,
    height: 0,
    position: 'absolute',
  },
  toggleSlider: {
    position: 'absolute',
    inset: 0,
    borderRadius: '999px',
    transition: 'background 0.2s ease',
  },
  toggleKnob: {
    position: 'absolute',
    left: '3px',
    top: '3px',
    width: '14px',
    height: '14px',
    borderRadius: '999px',
    background: '#ffffff',
    transition: 'transform 0.2s ease',
  },
  settingsFooterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  settingsVersionText: {
    margin: 0,
    color: '#4b5563',
    fontSize: '12px',
    textAlign: 'center',
  },
  actionsRowCompact: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  tableRowActive: {
    background: 'rgba(124, 58, 237, 0.08)',
  },
  profileCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  profileName: {
    color: '#f3f4f6',
    fontSize: '14px',
    fontWeight: 600,
  },
  profileStatusBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: '8px',
    padding: '4px 8px',
    background: 'rgba(124, 58, 237, 0.32)',
    color: '#ddd6fe',
    fontSize: '11px',
    fontWeight: 600,
  },
  primaryGhostButton: {
    background: '#374151',
    border: '1px solid #4b5563',
    color: '#f3f4f6',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  settingsTwoColumnGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '16px',
  },
  platformConnectionCard: {
    padding: '18px 20px',
  },
  platformConnectionRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
  },
  platformConnectionIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    border: '1px solid transparent',
    display: 'grid',
    placeItems: 'center',
    fontSize: '12px',
    fontWeight: 700,
    flexShrink: 0,
  },
  platformConnectionContent: {
    flex: 1,
    display: 'grid',
    gap: '10px',
    minWidth: 0,
  },
  platformConnectionHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
  },
  platformConnectionTitle: {
    margin: 0,
    color: '#f3f4f6',
    fontSize: '16px',
    fontWeight: 600,
  },
  platformConnectionMeta: {
    margin: '4px 0 0',
    fontSize: '14px',
    lineHeight: 1.45,
  },
  settingsTokenChip: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: '999px',
    background: '#374151',
    color: '#d1d5db',
    padding: '4px 8px',
    fontSize: '11px',
    fontWeight: 500,
  },
  disabledButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#6b7280',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'not-allowed',
    fontSize: '13px',
    fontWeight: 600,
  },
};
