import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    margin: 0,
    background: '#0b1020',
    color: '#e5e7eb',
    display: 'grid',
    placeItems: 'center',
    fontFamily: 'Inter, Segoe UI, sans-serif',
    padding: '24px',
  },
  card: {
    width: 'min(920px, 100%)',
    background: '#111827',
    border: '1px solid #1f2937',
    borderRadius: '12px',
    padding: '24px',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
  },
  title: {
    margin: 0,
    fontSize: '24px',
    fontWeight: 700,
  },
  meta: {
    margin: '8px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
  },
  sectionTabs: {
    marginTop: '18px',
    display: 'flex',
    gap: '8px',
  },
  tabButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#d1d5db',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  tabButtonActive: {
    background: '#1e1b4b',
    border: '1px solid #8b5cf6',
    color: '#f3e8ff',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  block: {
    marginTop: '16px',
    borderTop: '1px solid #1f2937',
    paddingTop: '16px',
  },
  subtitle: {
    margin: 0,
    fontSize: '18px',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '16px',
    color: '#e5e7eb',
  },
  settingsSection: {
    marginTop: '14px',
    display: 'grid',
    gap: '10px',
  },
  message: {
    margin: '8px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
  },
  error: {
    margin: '12px 0 0',
    color: '#fca5a5',
    fontSize: '14px',
  },
  list: {
    marginTop: '8px',
    display: 'grid',
    gap: '8px',
  },
  profileButton: {
    background: '#111827',
    border: '1px solid #374151',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  profileButtonActive: {
    background: '#1e1b4b',
    border: '1px solid #8b5cf6',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  path: {
    color: '#9ca3af',
    fontSize: '12px',
    wordBreak: 'break-all',
  },
  secondaryButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  actionsRow: {
    marginTop: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  dangerButton: {
    background: '#3f1d2e',
    border: '1px solid #7f1d1d',
    color: '#fecaca',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.65)',
    display: 'grid',
    placeItems: 'center',
    padding: '24px',
  },
  modalCard: {
    width: 'min(520px, 100%)',
    background: '#111827',
    border: '1px solid #374151',
    borderRadius: '12px',
    padding: '20px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '22px',
    fontWeight: 700,
  },
  label: {
    marginTop: '16px',
    display: 'grid',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  select: {
    background: '#1f2937',
    border: '1px solid #4b5563',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
  },
  checkboxLabel: {
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  modalActions: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  primaryButton: {
    background: '#7c3aed',
    border: '1px solid #8b5cf6',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '10px 14px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
  },
};
