import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    margin: 0,
    background: '#0b1020',
    color: '#e5e7eb',
    display: 'grid',
    placeItems: 'center',
    fontFamily: 'Inter, Segoe UI, sans-serif',
    padding: '24px',
  },
  card: {
    width: 'min(920px, 100%)',
    background: '#111827',
    border: '1px solid #1f2937',
    borderRadius: '12px',
    padding: '24px',
  },
  dashboardShell: {
    marginTop: '16px',
    display: 'grid',
    gap: '16px',
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.6fr) minmax(280px, 0.9fr)',
    gap: '16px',
    alignItems: 'start',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
  },
  title: {
    margin: 0,
    fontSize: '24px',
    fontWeight: 700,
  },
  meta: {
    margin: '8px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
  },
  sectionTabs: {
    marginTop: '18px',
    display: 'flex',
    gap: '8px',
  },
  tabButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#d1d5db',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  tabButtonActive: {
    background: '#1e1b4b',
    border: '1px solid #8b5cf6',
    color: '#f3e8ff',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  block: {
    marginTop: '16px',
    borderTop: '1px solid #1f2937',
    paddingTop: '16px',
  },
  subtitle: {
    margin: 0,
    fontSize: '18px',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '16px',
    color: '#e5e7eb',
  },
  settingsSection: {
    marginTop: '14px',
    display: 'grid',
    gap: '10px',
  },
  settingsGrid: {
    marginTop: '14px',
    display: 'grid',
    gap: '14px',
  },
  previewCard: {
    background: 'linear-gradient(180deg, rgba(17,24,39,0.98), rgba(11,16,32,0.96))',
    border: '1px solid #243041',
    borderRadius: '14px',
    padding: '16px',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
  },
  previewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  message: {
    margin: '8px 0 0',
    color: '#9ca3af',
    fontSize: '14px',
  },
  helper: {
    margin: '6px 0 0',
    color: '#6b7280',
    fontSize: '12px',
    lineHeight: 1.5,
  },
  error: {
    margin: '12px 0 0',
    color: '#fca5a5',
    fontSize: '14px',
  },
  list: {
    marginTop: '8px',
    display: 'grid',
    gap: '8px',
  },
  profileButton: {
    background: '#111827',
    border: '1px solid #374151',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  profileButtonActive: {
    background: '#1e1b4b',
    border: '1px solid #8b5cf6',
    color: '#e5e7eb',
    padding: '12px',
    borderRadius: '10px',
    textAlign: 'left',
    display: 'grid',
    gap: '4px',
    cursor: 'pointer',
  },
  feedCard: {
    background: 'linear-gradient(180deg, rgba(15,23,42,0.98), rgba(2,6,23,0.94))',
    border: '1px solid #243041',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 18px 36px rgba(0, 0, 0, 0.25)',
  },
  feedHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 16px',
    borderBottom: '1px solid #243041',
  },
  feedScroll: {
    maxHeight: '420px',
    overflowY: 'auto',
    display: 'grid',
    gap: '8px',
    padding: '12px',
  },
  chatItem: {
    display: 'grid',
    gap: '6px',
    padding: '12px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
  },
  chatMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    fontSize: '12px',
    color: '#94a3b8',
  },
  chatBody: {
    margin: 0,
    color: '#e5e7eb',
    fontSize: '14px',
    lineHeight: 1.5,
  },
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
  },
  statusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderRadius: '999px',
    background: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid #243041',
    color: '#e2e8f0',
    fontSize: '12px',
    fontWeight: 600,
  },
  statusDotOn: {
    width: '8px',
    height: '8px',
    borderRadius: '999px',
    background: '#22c55e',
    boxShadow: '0 0 0 4px rgba(34, 197, 94, 0.16)',
  },
  statusDotOff: {
    width: '8px',
    height: '8px',
    borderRadius: '999px',
    background: '#ef4444',
    boxShadow: '0 0 0 4px rgba(239, 68, 68, 0.16)',
  },
  sideStack: {
    display: 'grid',
    gap: '16px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
  },
  statCard: {
    padding: '12px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    display: 'grid',
    gap: '6px',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: '12px',
  },
  statValue: {
    color: '#f8fafc',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueGood: {
    color: '#4ade80',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueWarn: {
    color: '#facc15',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  statValueBad: {
    color: '#f87171',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.1,
  },
  platformCard: {
    padding: '14px',
    borderRadius: '14px',
    background: 'rgba(15, 23, 42, 0.84)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    display: 'grid',
    gap: '10px',
  },
  platformHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  tokenField: {
    width: '100%',
    background: '#0f172a',
    border: '1px solid #334155',
    color: '#cbd5e1',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  toastStack: {
    position: 'fixed',
    top: '16px',
    right: '16px',
    display: 'grid',
    gap: '10px',
    zIndex: 80,
  },
  toast: {
    minWidth: '260px',
    maxWidth: '360px',
    background: 'rgba(15, 23, 42, 0.96)',
    border: '1px solid rgba(248, 113, 113, 0.5)',
    borderRadius: '14px',
    padding: '12px 14px',
    color: '#fecaca',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.35)',
    display: 'grid',
    gap: '6px',
  },
  toastTitle: {
    color: '#fee2e2',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  eventBanner: {
    display: 'grid',
    gap: '6px',
    padding: '12px',
    borderRadius: '14px',
    background: 'linear-gradient(135deg, rgba(30,41,59,0.92), rgba(15,23,42,0.96))',
    border: '1px solid rgba(71, 85, 105, 0.7)',
  },
  eventHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  eventTitle: {
    color: '#f8fafc',
    fontSize: '14px',
    fontWeight: 700,
  },
  eventText: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  path: {
    color: '#9ca3af',
    fontSize: '12px',
    wordBreak: 'break-all',
  },
  secondaryButton: {
    background: '#1f2937',
    border: '1px solid #374151',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  actionsRow: {
    marginTop: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  dangerButton: {
    background: '#3f1d2e',
    border: '1px solid #7f1d1d',
    color: '#fecaca',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.65)',
    display: 'grid',
    placeItems: 'center',
    padding: '24px',
  },
  modalCard: {
    width: 'min(520px, 100%)',
    background: '#111827',
    border: '1px solid #374151',
    borderRadius: '12px',
    padding: '20px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '22px',
    fontWeight: 700,
  },
  label: {
    marginTop: '16px',
    display: 'grid',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  searchInput: {
    width: '100%',
    background: '#0f172a',
    border: '1px solid #334155',
    color: '#e5e7eb',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '14px',
  },
  select: {
    background: '#1f2937',
    border: '1px solid #4b5563',
    color: '#e5e7eb',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
  },
  checkboxLabel: {
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#d1d5db',
    fontSize: '14px',
  },
  pickerSurface: {
    marginTop: '10px',
    display: 'grid',
    gap: '10px',
    padding: '12px',
    background: 'rgba(15, 23, 42, 0.82)',
    border: '1px solid #243041',
    borderRadius: '12px',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  chip: {
    background: 'rgba(30, 41, 59, 0.95)',
    border: '1px solid #334155',
    color: '#cbd5e1',
    borderRadius: '999px',
    padding: '7px 11px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600,
  },
  chipActive: {
    background: 'rgba(14, 165, 233, 0.18)',
    border: '1px solid #38bdf8',
    color: '#e0f2fe',
    borderRadius: '999px',
    padding: '7px 11px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
  },
  selectionPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(14, 165, 233, 0.12)',
    border: '1px solid rgba(56, 189, 248, 0.35)',
    color: '#bae6fd',
    borderRadius: '999px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  listbox: {
    display: 'grid',
    gap: '8px',
    maxHeight: '230px',
    overflowY: 'auto',
  },
  listboxButton: {
    width: '100%',
    background: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid #243041',
    color: '#e5e7eb',
    borderRadius: '12px',
    padding: '12px',
    cursor: 'pointer',
    textAlign: 'left',
    display: 'grid',
    gap: '2px',
  },
  listboxButtonActive: {
    width: '100%',
    background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.18), rgba(14, 165, 233, 0.1))',
    border: '1px solid #38bdf8',
    color: '#f8fafc',
    borderRadius: '12px',
    padding: '12px',
    cursor: 'pointer',
    textAlign: 'left',
    display: 'grid',
    gap: '2px',
  },
  listboxMeta: {
    color: '#94a3b8',
    fontSize: '12px',
  },
  modalActions: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  primaryButton: {
    background: '#7c3aed',
    border: '1px solid #8b5cf6',
    color: '#ffffff',
    borderRadius: '8px',
    padding: '10px 14px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
  },
};
